apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuel-feed
  labels:
    app: nuel-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nuel-feed
  template:
    metadata:
      labels:
        app: nuel-feed
    spec:
      containers:
       - name: udagram-feed
         image: nuel07/udagram-api-feed:v2
         imagePullPolicy: Always
         resources:
           requests:
             memory: "128Mi"
             cpu: "250m"
           limits:
             memory: "1024Mi"
             cpu: "500m"
         ports:
         - containerPort: 8080
