apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuel-user
  labels:
    app: nuel-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nuel-user
  template:
    metadata:
      labels:
        app: nuel-user
    spec:
      containers:
       - name: udagram-user
         image: nuel07/udagram-api-user:v2
         imagePullPolicy: Always
         resources:
           requests:
             memory: "128Mi"
             cpu: "250m"
           limits:
             memory: "1024Mi"
             cpu: "500m"
         ports:
         - containerPort: 8080

