apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuel-frontend
  labels:
    app: nuel-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nuel-frontend
  template:
    metadata:
      labels:
        app: nuel-frontend
    spec:
      containers:
       - name: udagram-frontend
         image: nuel07/udagram-frontend:v3a
         imagePullPolicy: Always
         resources:
           requests:
             memory: "64Mi"
             cpu: "500m"
           limits:
             memory: "1024Mi"
             cpu: "500m"
         ports:
         - containerPort: 8080
