apiVersion: v1
kind: Service
metadata:
  name: nuel-reverseproxy
  labels:
    run: nuel-reverseproxy
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: nuel-reverseproxy
